### ISSUE TITLE
update gem on rubygems.org to support omniauth-oauth2 (~> 1.8) 

### ISSUE THREAD

**Issue by JacobMarq** [omniauth/omniauth-github#103]
There was a commit made yesterday 9/16/2022 that updated the gemspec to allow omniauth-oauth2 v1.8 but the gem when required from rubygems still depends on v1.7.1. Refencing the repo works around this but would appreciate an update if possible!👍🏻

**Comment by BobbyMcWho** [comment]
https://rubygems.org/gems/omniauth-github/versions/2.0.1
