### ISSUE TITLE
OAuth2::Error at /auth/github/callback bad_verification_code: error=bad_verification_code

### ISSUE THREAD

**Issue by tombell** [omniauth/omniauth-github#33]
I keep getting this exception occur when trying to authenticate via GitHub.

**Comment by FlorianLoch** [comment]
The problem still occurs for me - did you find a solution or a workaround?

**Comment by anasilva65** [comment]
did you manage to solve? give me the resolution please

**Comment by FlorianLoch** [comment]
This is so long ago - I do not even remember the project I used this for… soy sorry, cannot help you with that.
