### ISSUE TITLE
Setup automated testing 

### ISSUE THREAD

**Issue by andrew** [omniauth/omniauth-github#67]
Would be good to have travis-ci or circle ci run the test suite on pull requests and master after merges.

**Comment by tmilewski** [comment]
Apologies, I can't right now.

<img width="434" alt="screen shot 2017-02-06 at 9 56 21 pm" src="https://cloud.githubusercontent.com/assets/26691/22676042/2f8138bc-ecb7-11e6-9a75-83a7fab258b1.png">

 I'll see what I can do. Might make more sense to get this moved over to the Omniauth organization.
