### ISSUE TITLE
Follow/mention SemVer compliance in README

### ISSUE THREAD

**Issue by pravi** [omniauth/omniauth-github#77]
Even though SemVer seems a good thing, many projects don't follow it. So I'm on a mission to ask each project to make them SemVer compliance explicit. You can see the responses I recieved so far at https://wiki.debian.org/Teams/Ruby/UpstreamPledge

Please follow SemVer and if you already do, please mention it in README. This will help in projects like gitlab which currently has ~> 1.1.1 in their Gemfile to relax it to ~> 1.1. Such a change will make maintaining debian packages easier as I can update omniauth-github  without having to maintain a patch to gitlab.

**Comment by BobbyMcWho** [comment]
resolved by https://github.com/omniauth/omniauth-github/commit/d001ed274276bf50e1e756bf38bce75509aa25ec
