### ISSUE TITLE
Request access to cut new versions of Gem

### ISSUE THREAD

**Issue by supernova32** [omniauth/omniauth-github#87]
As discussed [here](https://github.com/omniauth/omniauth-github/pull/84) by @casperisfine and @BobbyMcWho, we should give access to RubyGems to one of the active maintainers of this project, so that new gem versions can be released. 

Current owners are @mbleigh and @tmilewski. Guys, can you give either @BobbyMcWho or me access to RubyGems to cut a new version?

**Comment by mbleigh** [comment]
@BobbyMcWho you now have publish access for the gem (trying to be careful here since I'm so out of the loop on this project, and you are already a publisher on `hashie` which is a good sign :smiley_cat:). Use it wisely!

**Comment by oblakeerickson** [comment]
@mbleigh thank you!

**Comment by BobbyMcWho** [comment]
Thanks @mbleigh! If you wanted to add me to omniauth/omniauth as well, there's a few merged commits there that have been waiting release as well
