### ISSUE TITLE
Can you please tag a new release?

### ISSUE THREAD

**Issue by patrobinson** [omniauth/omniauth-github#88]
Given the issues with getting access to Rubygems, we're switching to using a git source.

I'd rather not fetch from the `master` branch, so are you able to tag a new release which includes the changes in #84 ?

**Comment by BobbyMcWho** [comment]
I'd rather not tag a release til we're 100% certain we can release it. You can pin it to a commit sha in your Gemfile if you want to be safe.

https://bundler.io/guides/git.html

`gem 'omniauth-github', git: 'https://github.com/omniauth/omniauth-github.git', ref: '967d769' `

**Comment by ys** [comment]
I cannot wait for a gem to be cut for this. I don't want to rely on git SHAs in my Gemfile:) 

I hope we will get a new version soon!

Thanks for the work here, I really appreciate how quickly this has been fixed :)

**Comment by BobbyMcWho** [comment]
Published [1.4.0](https://github.com/omniauth/omniauth-github/releases/tag/v1.4.0)

**Comment by emq** [comment]
> Published 1.4.0

![](https://media.giphy.com/media/a3IWyhkEC0p32/giphy.gif)
