### ISSUE TITLE
Access_token query parameter is going to be deprecated

### ISSUE THREAD

**Issue by gionn** [omniauth/omniauth-github#89]
```
Please use the Authorization HTTP header instead as using the access_token query parameter is deprecated and will be removed July 1st, 2020.
```

ref: https://community.zammad.org/t/github-login-deprecation-notice-with-zammad-2-10-0/3986

**Comment by BobbyMcWho** [comment]
Hello @gionn,

Can you please add what version of omniauth-github you are seeing this in? I believe this should have been fixed as of the last minor version release 1.4.0

https://github.com/omniauth/omniauth-github/pull/84

**Comment by gionn** [comment]
https://github.com/zammad/zammad/blob/develop/Gemfile.lock#L324

I'll ask to upstream project maintainers to upgrade to 1.4.0 to see if it solve.

Thanks for your prompt reply!

**Comment by BobbyMcWho** [comment]
@gionn feel free to reopen if that for some reason didn't work for you
