### ISSUE TITLE
rails on undefiend `use` method

### ISSUE THREAD

**Issue by Anthonyntilelli** [omniauth/omniauth-github#91]
on rails you will get an error for undefined `use` method ([similar](https://github.com/tradegecko/omniauth-tradegecko/issues/2)) solution is to `Rails.application.config.middleware.use OmniAuth::Builder`  on rails.

**Comment by Anthonyntilelli** [comment]
Created a merge request to address issue:
https://github.com/omniauth/omniauth-github/pull/92

**Comment by nieisnuje** [comment]
h

**Comment by oblakeerickson** [comment]
Closing this because #92 has been merged. Thanks!
