### ISSUE TITLE
OmniAuth v2.0.0rc1

### ISSUE THREAD

**Issue by BobbyMcWho** [omniauth/omniauth-github#94]
Hello, maintainer of OmniAuth here (and also of this gem 😄 ).

I just wanted to make the maintainers of this gem aware of the discussion that I have opened regarding v2.0.0 of OmniAuth. I invite you to join in and voice any concerns you may have here: https://github.com/omniauth/omniauth/discussions/1017

**Comment by walro** [comment]
Seeing that [v2.0.0](https://github.com/omniauth/omniauth/releases/tag/v2.0.0) is now released it would be awesome to loosen the requirement on omniauth: https://github.com/omniauth/omniauth-github/blob/5afe8aee3baccd84ce6f265a3e62efbb55ac14b9/omniauth-github.gemspec#L19 (or start to require require 2.x)

**Comment by BobbyMcWho** [comment]
I have release [v2.0 of this gem](https://github.com/omniauth/omniauth-github/releases/tag/v2.0.0) and pushed to rubygems.

**Comment by walro** [comment]
Awesome, thanks!
